services:
  - type: web
    name: clothing-store-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_HOST
        fromDatabase:
          name: clothing-store-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: clothing-store-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clothing-store-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: clothing-store-db
          property: name
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "24h"

databases:
  - name: clothing-store-db
    databaseName: myropitacarrillochi
    user: clothing_store_user 